# Python for Actuaries Part 3
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ktnspr/py4ac/blob/main/03_python_pandas.ipynb) [![Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/ktnspr/py4ac/blob/main/03_python_pandas.ipynb)
## Agenda
In this notebook, we will cover:
- Introduction to Pandas
- Series and DataFrames
- Data access and inspection
- Data manipulation and cleaning
- Reading files

# Introduction to Pandas

**Pandas** is one of the most popular libraries for data analysis and manipulation in Python. It was specifically designed to work efficiently and easily with structured data, similar to how spreadsheets like Excel operate.

Pandas provides two main structures for handling data:
- **Series**: A one-dimensional data structure, similar to a list or an array.
- **DataFrame**: A two-dimensional data structure, comparable to a table in a database or an Excel spreadsheet.

### Why Pandas?
Pandas is particularly useful when it comes to reading, processing, and analyzing large amounts of data. Typical tasks that Pandas simplifies include:
- Reading data from various formats (e.g., CSV, Excel, SQL databases).
- Efficient inspection and analysis of data.
- Data cleaning and manipulation (e.g., handling missing values, renaming columns).
- Transformation and aggregation of data for further analysis or visualizations.

Due to its broad functionality and ease of use, Pandas has become a standard tool for data analysis, especially in the fields of data science, financial analysis, and insurance.

In the following sections, we will look at the key features of Pandas and learn how to efficiently read, analyze, and clean data.

### Criticisms of Pandas

Although Pandas is a powerful library, there are also some criticisms to keep in mind:

1. **Memory and computational overhead**: Pandas is memory-intensive as it loads data into memory. With very large datasets, this can lead to performance issues. For large datasets that do not fit into RAM, alternative tools such as **Dask**, **PySpark**, or **Apache Arrow** should be considered, which are optimized for distributed processing.

2. **Complexity with large data pipelines**: For smaller projects and analyses, Pandas is very efficient. However, with larger data pipelines or complex data analyses, the code can become unwieldy and hard to maintain. In particular, dealing with many nested Pandas functions can make the code difficult to understand.

Despite these limitations, Pandas remains a powerful tool for most data analyses, especially with medium-sized datasets.

In [2]:
# To work with Pandas, it obviously needs to be imported
import pandas as pd
# Typically, NumPy is also needed (math package is crap :D)
import numpy as np

## Series = "one column in excel sheet"

A **Pandas Series** is a one-dimensional data structure that is comparable to a list or an array. It consists of a series of values, each associated with an index. Pandas Series can contain various data types such as integers, floating-point numbers, or strings.

### Properties of a Series:
- **Index**: Each Series has an associated index, which by default starts at 0 and increments, but can also be explicitly set (e.g., dates).
- **Homogeneous Data**: All elements of a Series have the same data type (like in arrays).

Series are useful when working with one-dimensional data, such as a list of damage amounts in an insurance portfolio.

## Example 1: Damage History Over Several Years

In this example, we will store the annual damage history of an insurance company as a Pandas Series.

In [3]:
# Claims history over five years
years = ['2018', '2019', '2020', '2021', '2022']
claims_history = pd.Series([10000, 15000, 13000, 12000, 11000], index=years)
print(claims_history)

2018    10000
2019    15000
2020    13000
2021    12000
2022    11000
dtype: int64

Another example is (synthetic) stock trends:

In [4]:
# Parameters for the simulation
np.random.seed(42)
days = pd.date_range(start='2023-01-01', periods=365, freq='D')
starting_price = 100  # Initial stock price
volatility = 0.02  # Stock volatility (2%)
expected_return = 0.001  # Expected daily return (0.1%)

# Generate daily changes based on Brownian motion
changes = np.random.normal(loc=expected_return, scale=volatility, size=len(days))

# Calculate stock prices using cumulative sum
prices = starting_price * np.exp(np.cumsum(changes))

# Create the Pandas Series
stock_series = pd.Series(prices, index=days)

# Display the first few days of the stock price series
print(stock_series.head(20))

2023-01-01    101.099428
2023-01-02    100.921116
2023-01-03    102.339217
2023-01-04    105.610051
2023-01-05    105.221798
2023-01-06    104.835006
2023-01-07    108.307240
2023-01-08    110.092475
2023-01-09    109.172719
2023-01-10    110.474244
2023-01-11    109.564570
2023-01-12    108.657362
2023-01-13    109.293695
2023-01-14    105.295754
2023-01-15    101.826944
2023-01-16    100.788977
2023-01-17     98.866689
2023-01-18     99.589558
2023-01-19     97.895133
2023-01-20     95.263883
Freq: D, dtype: float64

## DataFrames

A **DataFrame** is the core of Pandas and represents a two-dimensional, table-like data structure that contains columns and rows. One can think of a DataFrame as a collection of Pandas Series that share a common structure. Each column is assigned a unique name, and each row can be referenced by an index.

### Properties of a DataFrame:
- **Rows and Columns**: A DataFrame consists of rows and columns, with each column potentially having its own data type (e.g., one column with numeric values and another column with strings).
- **Flexible Indexing**: You can access both rows and columns using the index or column names.
- **Data Sources**: DataFrames can be created from various data sources, such as CSV files, Excel files, SQL databases, or even from dictionaries and lists in Python.

## Example 1: Creating a DataFrame for Insurance Data

In this example, we will create a DataFrame that contains some basic information about insurance policies, such as the policy ID, the insured person, the premium amount, and the number of claims.

In [6]:
# Creating a DataFrame
# Define the data
data = {
    'Policy_ID': pd.Series([101, 102, 103, 104, 105, 106, 107, 108, 109, 110], dtype='int64'),
    'Insured_Person': pd.Series(['John Smith', 'Emma Johnson', 'Michael Brown', 'Olivia Davis', 'William Miller',
                          'Sophia Wilson', 'James Moore', 'Isabella Taylor', 'Lucas Anderson', 'Mia Thomas'], dtype='string'),
    'Age': pd.Series([18, 47, 49, 14, 15, 31, 1, 54, 3, 16], dtype='int64'),
    'Premium_Amount': pd.Series([500, 600, 550, 620, 480, 700, 520, 610, 580, 540], dtype='float64'),
    'Claims': pd.Series([2, 1, 0, 3, 2, 1, 1, 0, 4, 2], dtype='int64'),
    'Policy_Start': pd.to_datetime(['2019-01-15', '2020-05-20', '2021-03-10', '2018-11-22',
                                    '2019-07-01', '2020-02-17', '2021-09-09', '2022-01-01',
                                    '2019-12-25', '2020-06-14'])
}

# Create the DataFrame
insurance_df = pd.DataFrame(data)

# Display the DataFrame
insurance_df

   Policy_ID   Insured_Person  Age  Premium_Amount  Claims Policy_Start
0        101       John Smith   18           500.0       2   2019-01-15
1        102     Emma Johnson   47           600.0       1   2020-05-20
2        103    Michael Brown   49           550.0       0   2021-03-10
3        104     Olivia Davis   14           620.0       3   2018-11-22
4        105   William Miller   15           480.0       2   2019-07-01
5        106    Sophia Wilson   31           700.0       1   2020-02-17
6        107      James Moore    1           520.0       1   2021-09-09
7        108  Isabella Taylor   54           610.0       0   2022-01-01
8        109   Lucas Anderson    3           580.0       4   2019-12-25
9        110       Mia Thomas   16           540.0       2   2020-06-14

Attention, the DataFrame does not have an explicit index. Therefore, the column ranges from 0 to 9 at the front.

In [7]:
# type of columns
insurance_df.dtypes

Policy_ID                  int64
Insured_Person    string[python]
Age                        int64
Premium_Amount           float64
Claims                     int64
Policy_Start      datetime64[ns]
dtype: object

Here's the translation:

Another example of time-dependent (synthetic) data:

In [8]:
# Parameters for the simulation
np.random.seed(42)
days = pd.date_range(start='2023-01-01', periods=365, freq='D')

# Stock parameters for different companies
companies = {
    'Apple': {'start_price': 150, 'volatility': 0.02, 'return': 0.001},
    'Nvidia': {'start_price': 220, 'volatility': 0.025, 'return': 0.0012},
    'Google': {'start_price': 180, 'volatility': 0.018, 'return': 0.0008},
    'SAP': {'start_price': 120, 'volatility': 0.015, 'return': 0.0009},
    'Microsoft': {'start_price': 250, 'volatility': 0.02, 'return': 0.0011},
    'Tesla': {'start_price': 200, 'volatility': 0.03, 'return': 0.0015},
}

# Create a DataFrame to store all stock trajectories
stock_prices = pd.DataFrame(index=days)

# Simulate stock prices for each company
for company, params in companies.items():
    start_price = params['start_price']
    volatility = params['volatility']
    expected_return = params['return']

    # Generate daily changes based on Brownian motion
    changes = np.random.normal(loc=expected_return, scale=volatility, size=len(days))

    # Calculate stock prices with cumulative sum
    prices = start_price * np.exp(np.cumsum(changes))

    # Add the simulation as a series in the DataFrame
    stock_prices[company] = prices

# Output the first 20 days of the simulated stock prices
stock_prices.head(20)

,Apple,Nvidia,Google,SAP,Microsoft,Tesla
2023-01-01,151.649142,218.065840,180.780225,119.962716,249.583068,202.973532
2023-01-02,151.381674,219.554248,177.766583,120.212441,243.814047,196.736174
2023-01-03,153.508826,219.887083,179.221040,116.767819,243.064142,205.550467
2023-01-04,158.415077,220.689351,173.950956,118.490457,239.227495,205.251066
2023-01-05,157.832697,216.725335,177.345215,119.215139,236.726269,205.675448
2023-01-06,157.252509,217.118561,179.003428,121.122194,239.793002,210.407444
2023-01-07,162.460860,220.102539,179.974197,116.077268,248.209748,212.202784
2023-01-08,165.138713,228.508205,183.332589,119.878856,250.452074,218.685898
2023-01-09,163.759079,234.335509,189.063033,119.735824,244.802048,220.908849
2023-01-10,165.711366,247.592302,192.700878,121.852414,247.260385,217.212698
2023-01-11,164.346855,243.179477,186.569420,120.074454,253.528084,219.910832
2023-01-12,162.986042,248.839417,182.467305,121.292334,250.730572,212.812260
2023-01-13,163.940542,250.282762,180.571040,119.498328,250.334644,213.826975
2023-01-14,157.943632,264.683930,180.800446,118.492047,250.683795,213.934578
2023-01-15,152.740416,259.700473,182.639045,122.053115,247.050902,212.922182
2023-01-16,151.183465,254.610747,180.412949,121.814096,250.550377,212.421101
2023-01-17,148.300034,251.125064,181.165357,122.322081,250.220128,201.062370
2023-01-18,149.384337,238.424736,178.861774,124.040557,252.606184,198.076518
2023-01-19,146.842700,235.593959,177.045361,125.078785,248.435151,198.927166
2023-01-20,142.895825,231.442507,172.757016,125.474193,246.542078,200.183501

Now we have two nice example datasets `insurance_df` and `stock_prices`. Let's see what we can do with them.

# Pandas Standard Functions

Pandas offers a range of helpful standard functions to quickly and efficiently inspect data. Here are some of the most important ones:
`head()` and `tail()`

With `head()` and `tail()`, you can display the first or last entries of a DataFrame or a Series. This is useful for getting a quick overview of the structure of the data. We have already seen examples (from `head()`) above.

More interesting for getting a first impression of a dataset are the functions `describe()` and `info()`.

In [14]:
insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Policy_ID       10 non-null     int64
 1   Insured_Person  10 non-null     string
 2   Age             10 non-null     int64
 3   Premium_Amount  10 non-null     float64
 4   Claims          10 non-null     int64
 5   Policy_Start    10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), string(1)
memory usage: 612.0 bytes

In [15]:
stock_prices.describe()

            Apple      Nvidia      Google         SAP   Microsoft       Tesla
count  365.000000  365.000000  365.000000  365.000000  365.000000  365.000000
mean   167.850773  247.333421  334.409550  171.437584  392.180590  285.122855
std     32.734342   25.403491  119.476135   27.567769  111.641143   42.962466
min    124.387660  196.124623  163.329860  116.077268  236.726269  194.397337
25%    138.046904  231.442507  219.369854  153.248588  301.510627  244.690657
50%    159.990521  250.038092  359.991431  168.130991  340.281680  297.725328
75%    189.656332  262.092442  419.665054  184.807960  498.434008  315.574291
max    239.182908  320.716569  554.977232  260.720802  636.691147  382.720169

Other important information includes, for example, `columns`, `index`, or `shape`. (Note that these are not functions but attributes of the DataFrame.)

In [16]:
stock_prices.columns

Index(['Apple', 'Nvidia', 'Google', 'SAP', 'Microsoft', 'Tesla'], dtype='object')

In [17]:
insurance_df.shape

(10, 6)

In [18]:
stock_prices.index

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-12-22', '2023-12-23', '2023-12-24', '2023-12-25',
               '2023-12-26', '2023-12-27', '2023-12-28', '2023-12-29',
               '2023-12-30', '2023-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')

## Data Access in Pandas

In Pandas, there are various methods to access data in a DataFrame. This includes accessing columns, rows, or specific elements using `loc` and `iloc`.

### Accessing Columns

A column of a DataFrame can be easily accessed using the column name. There are two ways to do this:

1. Access using dot notation

In [19]:
insurance_df.Insured_Person

0         John Smith
1       Emma Johnson
2      Michael Brown
3       Olivia Davis
4     William Miller
5      Sophia Wilson
6        James Moore
7    Isabella Taylor
8     Lucas Anderson
9         Mia Thomas
Name: Insured_Person, dtype: string

2. With column names in square brackets (more common)

In [24]:
insurance_df['Insured_Person']

0         John Smith
1       Emma Johnson
2      Michael Brown
3       Olivia Davis
4     William Miller
5      Sophia Wilson
6        James Moore
7    Isabella Taylor
8     Lucas Anderson
9         Mia Thomas
Name: Insured_Person, dtype: string

'## Accessing Rows

`loc[]` – Access by Labels (Index-based)

With 'loc[]', you can access rows and columns based on the labels. This method uses explicit index names or column names.

In [28]:
stock_prices.loc['01-01-2023'] #Watch out for the date format

Apple        151.649142
Nvidia       218.065840
Google       180.780225
SAP          119.962716
Microsoft    249.583068
Tesla        202.973532
Name: 2023-01-01 00:00:00, dtype: float64

`iloc[]` - Integer-based Access

With `iloc[]`, you access rows and columns based on their position in the DataFrame. This works similarly to a list in Python, where the indices are 0-based.

In [29]:
stock_prices.iloc[0] #first rows

Apple        151.649142
Nvidia       218.065840
Google       180.780225
SAP          119.962716
Microsoft    249.583068
Tesla        202.973532
Name: 2023-01-01 00:00:00, dtype: float64

## Accessing Columns and Rows + Slicing
You can also access columns and rows simultaneously, plus select only parts of the data (*slicing*).

In [30]:
# Only the first 5 days of the stock prices for Apple and Nvidia
stock_prices.loc['2023-01-01':'2023-01-05', ['Apple', 'Nvidia']]

                 Apple      Nvidia
2023-01-01  151.649142  218.065840
2023-01-02  151.381674  219.554248
2023-01-03  153.508826  219.887083
2023-01-04  158.415077  220.689351
2023-01-05  157.832697  216.725335

In [31]:
# Accessing a specific value in the DataFrame
insurance_df.iloc[2,1]

'Michael Brown'

In [32]:
stock_prices.loc['2023-12-31', 'Microsoft']

np.float64(484.4990301196811)

# Conditional Access

In addition to accessing data via column names or indices, you can also access data based on conditions.

In [34]:
# all contracts starting in May
insurance_df[insurance_df['Policy_Start'].dt.month == 5]

   Policy_ID Insured_Person  Age  Premium_Amount  Claims Policy_Start
1        102   Emma Johnson   47           600.0       1   2020-05-20

In [35]:
# only contracts with a premium amount greater than 600
insurance_df[insurance_df['Premium_Amount'] > 600]

   Policy_ID   Insured_Person  Age  Premium_Amount  Claims Policy_Start
3        104     Olivia Davis   14           620.0       3   2018-11-22
5        106    Sophia Wilson   31           700.0       1   2020-02-17
7        108  Isabella Taylor   54           610.0       0   2022-01-01

In [33]:
# access is given by a boolean mask
insurance_df['Premium_Amount'] > 600

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7     True
8    False
9    False
Name: Premium_Amount, dtype: bool

The conditional access is very powerful; however, it can also become very complex very quickly:

In [36]:
stock_prices[
    (stock_prices.index.month == 5) &  # Filter for May
    ((stock_prices['Nvidia'] > 230) |   # Nvidia > 230 or
    (stock_prices['Apple'] > 140)) &    # Apple > 155
    (stock_prices['Google'] > 185) &   # Google > 185
    (stock_prices['Tesla'] < 260)      # Tesla < 220
]

,Apple,Nvidia,Google,SAP,Microsoft,Tesla
2023-05-10,143.253302,275.343354,238.907208,155.546811,298.995232,255.879194
2023-05-12,139.347720,272.587721,233.701450,155.626138,276.651292,250.853311

## Enriching Data

In data analysis, it is often necessary to expand existing datasets by adding new columns. This can be done, for example, through calculations, importing additional data, or applying functions. In Pandas, there is a straightforward way to create new columns and fill them with data.

Typical use cases include:

- Calculating new values based on existing columns (e.g., risk assessments, premium calculations)
- Adding external data sources (e.g., inflation, exchange rates)
- Creating categories or groupings (e.g., age divisions, damage classes)

New columns can be created in various ways, such as through simple assignment, using calculations, or assigning a constant or calculated series of values.

In the following examples, we will look at how to add new columns to an existing DataFrame.

In [37]:
# add a column with the contract duration in years
insurance_df['Duration'] = (pd.to_datetime('today') - insurance_df['Policy_Start']).dt.days / 365
insurance_df

,Policy_ID,Insured_Person,Age,Premium_Amount,Claims,Policy_Start,Duration
0,101,John Smith,18,500.0,2,2019-01-15,7.178082
1,102,Emma Johnson,47,600.0,1,2020-05-20,5.832877
2,103,Michael Brown,49,550.0,0,2021-03-10,5.027397
3,104,Olivia Davis,14,620.0,3,2018-11-22,7.326027
4,105,William Miller,15,480.0,2,2019-07-01,6.720548
5,106,Sophia Wilson,31,700.0,1,2020-02-17,6.087671
6,107,James Moore,1,520.0,1,2021-09-09,4.526027
7,108,Isabella Taylor,54,610.0,0,2022-01-01,4.213699
8,109,Lucas Anderson,3,580.0,4,2019-12-25,6.235616
9,110,Mia Thomas,16,540.0,2,2020-06-14,5.764384

In [38]:
# Calculate the absolute performance relative to the starting value for Apple stock
stock_price_apple = pd.DataFrame()
stock_price_apple['Price'] = stock_prices['Apple']
start_value_apple = stock_price_apple['Price'].iloc[0]  # Starting value of the stock
print(f'Simulated starting value of Apple stock: {start_value_apple}')
stock_price_apple['AbsPerformance'] = stock_price_apple['Price'] - start_value_apple

# Display the last rows including the new column
print(stock_price_apple.tail())

Simulated starting value of Apple stock: 151.64914212169614
                 Price  AbsPerformance
2023-12-27  220.065965       68.416823
2023-12-28  227.143532       75.494390
2023-12-29  226.876749       75.227607
2023-12-30  228.935694       77.286552
2023-12-31  232.349808       80.700666

In addition to simple calculations, there are also Pandas standard functions for many use cases.

In [39]:
# Calculate the relative performance of Apple stock
stock_price_apple['RelPerformance'] = stock_price_apple['Price'].pct_change()
stock_price_apple.tail()

                 Price  AbsPerformance  RelPerformance
2023-12-27  220.065965       68.416823        0.011452
2023-12-28  227.143532       75.494390        0.032161
2023-12-29  226.876749       75.227607       -0.001175
2023-12-30  228.935694       77.286552        0.009075
2023-12-31  232.349808       80.700666        0.014913

## Delete Data
If you want to delete a column or row, you can do so by:

- **Deleting Rows**: You can remove specific rows using `drop(index)`. Here, you specify the index of the rows that should be deleted.
- **Deleting Columns**: You can remove specific columns using `drop(column_name, axis=1)`.

Inplace Option: If you want to apply the changes directly to the existing DataFrame, you can use `inplace=True` to avoid creating a copy of the DataFrame.

**Warning**: `drop()` does not allow reverting to the original data once the rows or columns have been deleted, unless a copy was created beforehand.

In [40]:
# Delete a column
stock_price_apple.drop(['RelPerformance'], axis=1)

                 Price  AbsPerformance
2023-01-01  151.649142        0.000000
2023-01-02  151.381674       -0.267468
2023-01-03  153.508826        1.859684
2023-01-04  158.415077        6.765935
2023-01-05  157.832697        6.183555
...                ...             ...
2023-12-27  220.065965       68.416823
2023-12-28  227.143532       75.494390
2023-12-29  226.876749       75.227607
2023-12-30  228.935694       77.286552
2023-12-31  232.349808       80.700666

[365 rows x 2 columns]

Drop returns a new dataframe without the deleted data. Without `inplace=True`, the original dataframe does not change.

In [41]:
stock_price_apple

                 Price  AbsPerformance  RelPerformance
2023-01-01  151.649142        0.000000             NaN
2023-01-02  151.381674       -0.267468       -0.001764
2023-01-03  153.508826        1.859684        0.014052
2023-01-04  158.415077        6.765935        0.031961
2023-01-05  157.832697        6.183555       -0.003676
...                ...             ...             ...
2023-12-27  220.065965       68.416823        0.011452
2023-12-28  227.143532       75.494390        0.032161
2023-12-29  226.876749       75.227607       -0.001175
2023-12-30  228.935694       77.286552        0.009075
2023-12-31  232.349808       80.700666        0.014913

[365 rows x 3 columns]

In [42]:
# Delete the third an fourth row
stock_price_apple.drop(['2023-01-03', '2023-01-04'], inplace=True) # Watch the index is a date
stock_price_apple.head()

                 Price  AbsPerformance  RelPerformance
2023-01-01  151.649142        0.000000             NaN
2023-01-02  151.381674       -0.267468       -0.001764
2023-01-05  157.832697        6.183555       -0.003676
2023-01-06  157.252509        5.603367       -0.003676
2023-01-07  162.460860       10.811717        0.033121

# Task: Working with Damage Data

In this task, you will perform various operations using a sample dataset of damage data. We will create the data using the following code:

In [50]:
# Creating example data
data = {
    'Claim_ID': range(1, 16),
    'Policy_Number': [f'PN{str(i).zfill(5)}' for i in np.random.randint(0, 10000, 15)],  # Random policy numbers
    'Claim_Amount': np.random.randint(1000, 5000, size=15),  # Random claim amounts between 1000 and 5000
    'Claim_Date': pd.date_range(start='2023-01-01', periods=15, freq='D'),
    'Policy_Start': pd.date_range(start='2021-01-01', periods=15, freq='D'),
    'Region': [
        'North', 'East', 'South', 'West', 'North',
        'East', 'South', 'West', 'North', 'East',
        'South', 'West', 'North', 'East', 'South'
    ]
}

## Tasks

1. **Create DataFrame**: Create a Pandas DataFrame from the data provided above.

2. **View Data**: Use the `head()` and `describe()` methods to get an overview of the dataset. What do you notice?

3. **Filter Data**: Filter the claims that have a claim amount of more than 2000. Which policyholders are affected?

4. **Determine Contract Duration**: Add a new column `Contract Duration` that indicates the duration of the contract in days until the date of the claim.

5. **Calculate Average Claim Amount**: Calculate the average claim amount of the claims.

6. **Group Claim Amounts**: Group the claim amounts by region.

## Note

You can use Pandas functions to solve the tasks mentioned above. Please note that we have not yet discussed the approach for task 6. Take a look at the documentation for `mean()` and `groupby()`. ([Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html#pandas.DataFrame.groupby))

You can obtain the number of different values in the *Region* column using the `value_counts()` function.

In [84]:
# Add your code here
claims_df = pd.DataFrame(data)
claims_df

    Claim_ID Policy_Number  Claim_Amount Claim_Date Policy_Start Region
0          1       PN09797          1796 2023-01-01   2021-01-01  North
1          2       PN09467          4642 2023-01-02   2021-01-02   East
2          3       PN02743          3172 2023-01-03   2021-01-03  South
3          4       PN07866          4425 2023-01-04   2021-01-04   West
4          5       PN07160          2296 2023-01-05   2021-01-05  North
5          6       PN05451          1618 2023-01-06   2021-01-06   East
6          7       PN05258          2834 2023-01-07   2021-01-07  South
7          8       PN08548          1244 2023-01-08   2021-01-08   West
8          9       PN07186          3895 2023-01-09   2021-01-09  North
9         10       PN06102          3497 2023-01-10   2021-01-10   East
10        11       PN09061          1929 2023-01-11   2021-01-11  South
11        12       PN09077          2270 2023-01-12   2021-01-12   West
12        13       PN09475          1519 2023-01-13   2021-01-13  North
13        14       PN00619          4212 2023-01-14   2021-01-14   East
14        15       PN00882          3409 2023-01-15   2021-01-15  South

In [85]:
claims_df.head()

   Claim_ID Policy_Number  Claim_Amount Claim_Date Policy_Start Region
0         1       PN09797          1796 2023-01-01   2021-01-01  North
1         2       PN09467          4642 2023-01-02   2021-01-02   East
2         3       PN02743          3172 2023-01-03   2021-01-03  South
3         4       PN07866          4425 2023-01-04   2021-01-04   West
4         5       PN07160          2296 2023-01-05   2021-01-05  North

In [88]:
claims_df.describe()

        Claim_ID  Claim_Amount           Claim_Date         Policy_Start
count  15.000000     15.000000                   15                   15
mean    8.000000   2850.533333  2023-01-08 00:00:00  2021-01-08 00:00:00
min     1.000000   1244.000000  2023-01-01 00:00:00  2021-01-01 00:00:00
25%     4.500000   1862.500000  2023-01-04 12:00:00  2021-01-04 12:00:00
50%     8.000000   2834.000000  2023-01-08 00:00:00  2021-01-08 00:00:00
75%    11.500000   3696.000000  2023-01-11 12:00:00  2021-01-11 12:00:00
max    15.000000   4642.000000  2023-01-15 00:00:00  2021-01-15 00:00:00
std     4.472136   1132.162209                  NaN                  NaN

In [87]:
claims_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Claim_ID       15 non-null     int64
 1   Policy_Number  15 non-null     object
 2   Claim_Amount   15 non-null     int64
 3   Claim_Date     15 non-null     datetime64[ns]
 4   Policy_Start   15 non-null     datetime64[ns]
 5   Region         15 non-null     object
dtypes: datetime64[ns](2), int64(2), object(2)
memory usage: 852.0+ bytes

In [89]:
claims_df[claims_df['Claim_Amount']>2000]

    Claim_ID Policy_Number  Claim_Amount Claim_Date Policy_Start Region
1          2       PN09467          4642 2023-01-02   2021-01-02   East
2          3       PN02743          3172 2023-01-03   2021-01-03  South
3          4       PN07866          4425 2023-01-04   2021-01-04   West
4          5       PN07160          2296 2023-01-05   2021-01-05  North
6          7       PN05258          2834 2023-01-07   2021-01-07  South
8          9       PN07186          3895 2023-01-09   2021-01-09  North
9         10       PN06102          3497 2023-01-10   2021-01-10   East
11        12       PN09077          2270 2023-01-12   2021-01-12   West
13        14       PN00619          4212 2023-01-14   2021-01-14   East
14        15       PN00882          3409 2023-01-15   2021-01-15  South

In [91]:
claims_df['Policy_Number'][claims_df['Claim_Amount']>2000]

1     PN09467
2     PN02743
3     PN07866
4     PN07160
6     PN05258
8     PN07186
9     PN06102
11    PN09077
13    PN00619
14    PN00882
Name: Policy_Number, dtype: object

In [97]:
claims_df['Contract Duration'] = (claims_df['Claim_Date'] - claims_df['Policy_Start']).dt.days
claims_df

,Claim_ID,Policy_Number,Claim_Amount,Claim_Date,Policy_Start,Region,Contract Duration
0,1,PN09797,1796,2023-01-01,2021-01-01,North,730
1,2,PN09467,4642,2023-01-02,2021-01-02,East,730
2,3,PN02743,3172,2023-01-03,2021-01-03,South,730
3,4,PN07866,4425,2023-01-04,2021-01-04,West,730
4,5,PN07160,2296,2023-01-05,2021-01-05,North,730
5,6,PN05451,1618,2023-01-06,2021-01-06,East,730
6,7,PN05258,2834,2023-01-07,2021-01-07,South,730
7,8,PN08548,1244,2023-01-08,2021-01-08,West,730
8,9,PN07186,3895,2023-01-09,2021-01-09,North,730
9,10,PN06102,3497,2023-01-10,2021-01-10,East,730
10,11,PN09061,1929,2023-01-11,2021-01-11,South,730
11,12,PN09077,2270,2023-01-12,2021-01-12,West,730
12,13,PN09475,1519,2023-01-13,2021-01-13,North,730
13,14,PN00619,4212,2023-01-14,2021-01-14,East,730
14,15,PN00882,3409,2023-01-15,2021-01-15,South,730

In [105]:
claims_df['Claim_Amount'].mean()
#claims_df['Claim_Amount'].median()

np.float64(2850.5333333333333)

In [104]:
claims_df.groupby('Region')['Claim_Amount'].mean()

Region
East     3492.250000
North    2376.500000
South    2836.000000
West     2646.333333
Name: Claim_Amount, dtype: float64

# Grouping Data and Aggregation Functions in Pandas

In data analysis, it is often necessary to group data in order to calculate aggregated statistics. Pandas provides powerful functions to group data and perform various aggregation operations.

## Basic Concepts

- **Grouping**: Data is grouped using the `groupby()` method. This method splits the data into groups based on the values of one or more columns.
- **Aggregation**: After grouping, various aggregation functions can be applied to calculate statistical measures. Commonly used aggregation functions include:
  - `mean()`: Calculates the average.
  - `sum()`: Calculates the sum.
  - `count()`: Counts the number of elements.
  - `max()`: Determines the maximum value.
  - `min()`: Determines the minimum value.

## Example: Aggregating Damage Data

Suppose we have a DataFrame `damage_data` with damage information, which contains a column for the region and one for the amount of damage. We can calculate the average damage per region as follows:

```python
average_damage = damage_data.groupby('Region')['Damage Amount'].mean()
print(average_damage)
```

# Pivoting with Pandas

Pivoting in Pandas allows you to transform data into a clear table, similar to pivot tables in Excel. With the `pivot()` function, you can restructure data based on key columns (such as categories, regions, or time indicators). One column is used for the values you want to aggregate or display, while other columns are used as the index or column headers.

## Example of Pivoting:

Suppose we want to create an overview of the average damage amount in different regions.

In [108]:
# Create a pivot table showing the mean claim amounts by region
claim_pivot = claims_df.pivot_table(values='Claim_Amount', index='Region', aggfunc='mean')
claim_pivot

        Claim_Amount
Region
East     3492.250000
North    2376.500000
South    2836.000000
West     2646.333333

# Reading and Writing Data in Pandas DataFrames

Pandas offers powerful functions for reading data from various file formats and writing DataFrames to files. The most common formats are CSV (Comma-Separated Values) and Excel, but it also supports JSON, HTML, LaTeX, Parquet, SAS, and more.

## Reading Data
To read data from a CSV file into a Pandas DataFrame, use the `read_csv()` function. Here is an example:

```python
import pandas as pd

# Reading a CSV file
df_csv = pd.read_csv('path/to/file.csv')

# Output the first five rows of the DataFrame
print(df_csv.head())
```

Reading an Excel file is just as simple:
```python
# Reading an Excel file
df_excel = pd.read_excel('path/to/file.xlsx', sheet_name='Sheet1')

# Output the first five rows of the DataFrame
print(df_excel.head())
```

## Writing Data
To write a DataFrame to a CSV file, use the `to_csv()` function. Here is an example:
```python
# Writing the DataFrame to a CSV file
df_csv.to_csv('path/to/new_file.csv', index=False)
```

Or:
```python
# Writing the DataFrame to an Excel file
df_excel.to_excel('path/to/new_file.xlsx', sheet_name='Sheet1', index=False)
```

# Reading Files from Non-Local Sources

You can easily read data sources with `pandas` that are not local but rather "somewhere" on the internet or on a server. You just need to specify the URL to the location of the file.

For example, we can read files from a GitHub repository like this:

In [109]:
# Watch for the "raw" part of the URL
data = pd.read_csv('https://raw.githubusercontent.com/DeutscheAktuarvereinigung/Python_fuer_Aktuare/refs/heads/main/data/weather_data.csv')
data.head()

         Date  Temperature (Celsius)  Humidity (%)  Precipitation (mm)
0  2018-01-01              -3.045451     25.000000           14.346340
1  2018-01-02               4.983468     50.733140           27.050607
2  2018-01-03               0.801434     25.000000           18.583728
3  2018-01-04               2.031394     33.203715           16.564713
4  2018-01-05               8.502787     25.000000           12.848124

## Handling Missing Data

In real datasets, missing data is a common problem. Pandas offers a variety of methods to identify, handle, or clean missing values.

### Detecting Missing Data
With the function `isnull()` or `isna()`, you can identify which entries are missing in a DataFrame. `isnull()` returns `True` if the value is missing (NaN) and `False` if a valid value is present.

Let's take a look at this using our insurance dataset from above.

In [110]:
# So far the dataset has no missing values, so we'll create some
nan_df = insurance_df.copy()

# Randomly insert NaN values (approx. 25% of the data)
for col in ['Age', 'Policy_Start', 'Duration']:
    nan_df.loc[nan_df.sample(frac=0.25).index, col] = np.nan

nan_df

,Policy_ID,Insured_Person,Age,Premium_Amount,Claims,Policy_Start,Duration
0,101,John Smith,18.0,500.0,2,2019-01-15,7.178082
1,102,Emma Johnson,NaN,600.0,1,2020-05-20,5.832877
2,103,Michael Brown,49.0,550.0,0,NaT,5.027397
3,104,Olivia Davis,14.0,620.0,3,2018-11-22,7.326027
4,105,William Miller,15.0,480.0,2,2019-07-01,6.720548
5,106,Sophia Wilson,31.0,700.0,1,2020-02-17,6.087671
6,107,James Moore,1.0,520.0,1,2021-09-09,NaN
7,108,Isabella Taylor,54.0,610.0,0,2022-01-01,4.213699
8,109,Lucas Anderson,NaN,580.0,4,NaT,NaN
9,110,Mia Thomas,16.0,540.0,2,2020-06-14,5.764384

In [111]:
nan_df.isna()

,Policy_ID,Insured_Person,Age,Premium_Amount,Claims,Policy_Start,Duration
0,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False
2,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False
8,False,False,True,False,False,True,True
9,False,False,False,False,False,False,False

In [112]:
nan_df.isnull().sum()

Policy_ID         0
Insured_Person    0
Age               2
Premium_Amount    0
Claims            0
Policy_Start      2
Duration          2
dtype: int64

In [113]:
nan_df.info() #you can see number of null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Policy_ID       10 non-null     int64
 1   Insured_Person  10 non-null     string
 2   Age             8 non-null      float64
 3   Premium_Amount  10 non-null     float64
 4   Claims          10 non-null     int64
 5   Policy_Start    8 non-null      datetime64[ns]
 6   Duration        8 non-null      float64
dtypes: datetime64[ns](1), float64(3), int64(2), string(1)
memory usage: 692.0 bytes

## Remove Missing Data

With `dropna()`, you can remove rows or columns with missing values. You can control whether to consider all missing values (how='all') or only individual missing values (how='any').

In [114]:
df_cleaned = nan_df.dropna()
df_cleaned

,Policy_ID,Insured_Person,Age,Premium_Amount,Claims,Policy_Start,Duration
0,101,John Smith,18.0,500.0,2,2019-01-15,7.178082
3,104,Olivia Davis,14.0,620.0,3,2018-11-22,7.326027
4,105,William Miller,15.0,480.0,2,2019-07-01,6.720548
5,106,Sophia Wilson,31.0,700.0,1,2020-02-17,6.087671
7,108,Isabella Taylor,54.0,610.0,0,2022-01-01,4.213699
9,110,Mia Thomas,16.0,540.0,2,2020-06-14,5.764384

### Filling Missing Data

Instead of removing missing values, we can also replace them with meaningful values. This can be, for example, the mean, median, or a specified value. Use the `fillna()` function for this purpose.

In [116]:
nan_df['Age'].fillna(nan_df['Age'].mean(), inplace=True)
nan_df

/tmp/ipykernel_1755/3601872766.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  nan_df['Age'].fillna(nan_df['Age'].mean(), inplace=True)

,Policy_ID,Insured_Person,Age,Premium_Amount,Claims,Policy_Start,Duration
0,101,John Smith,18.00,500.0,2,2019-01-15,7.178082
1,102,Emma Johnson,24.75,600.0,1,2020-05-20,5.832877
2,103,Michael Brown,49.00,550.0,0,NaT,5.027397
3,104,Olivia Davis,14.00,620.0,3,2018-11-22,7.326027
4,105,William Miller,15.00,480.0,2,2019-07-01,6.720548
5,106,Sophia Wilson,31.00,700.0,1,2020-02-17,6.087671
6,107,James Moore,1.00,520.0,1,2021-09-09,NaN
7,108,Isabella Taylor,54.00,610.0,0,2022-01-01,4.213699
8,109,Lucas Anderson,24.75,580.0,4,NaT,NaN
9,110,Mia Thomas,16.00,540.0,2,2020-06-14,5.764384

# Task
Now it's your turn. In the *data* folder, you will find two datasets:
- car_insurance_claims.csv (Car insurance data)
- titanic_train.csv (Titanic passenger data)

Source:

The car insurance data comes from [Databrick](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/4954928053318020/1058911316420443/167703932442645/latest.html). Unfortunately, no further source is provided there.

The Titanic data is taken from the [Titanic Machine Learning Challenge](https://www.kaggle.com/c/titanic/data) on Kaggle and contains data from 892 Titanic passengers. The dataset is used in the challenge for training machine learning algorithms.

## Tasks for the Damage Case Dataset

1. Get an Overview
- **Task**: Read in the dataset and get an overview.
  - Use `head()` to view the first 5 rows of the dataset.
  - Use `info()` to obtain information about the data types and the number of entries.
  - Display a summary of the numerical columns with `describe()`.

*Note* The link to the online storage location of the data is:
https://raw.githubusercontent.com/DeutscheAktuarvereinigung/Python_fuer_Aktuare/refs/heads/completed/data/car_insurance_claims.csv

2. Column Access and Simple Calculations
- **Task**: Work with individual columns.
  - Show the average amount of the `total_claim_amount`.
  - Find the maximum and minimum value for the `policy_annual_premium` column.
  - Create a new column `claim_ratio` that calculates the ratio of `total_claim_amount` to `policy_annual_premium`.

3. Filtering Data
- **Task**: Filter the dataset based on specific conditions.
  - Find all cases where the `incident_type` is reported as "Single Vehicle Collision".
  - Display all incidents that occurred in the state "NY" (`incident_state`) and where the claim amount (`total_claim_amount`) is over 10,000.
  - Find all incidents where more than 2 witnesses (`witnesses`) were reported.

4. Grouping and Aggregating
- **Task**: Group data and calculate averages.
  - Group the data by `incident_state` and show the average `total_claim_amount` for each state.
  - Group the data by `insured_occupation` and display the mean amount of `injury_claim`.
  - Find the average `property_claim` by `auto_make`.

5. Handling Missing Data
- **Task**: Deal with missing data.
  - Determine which columns contain missing values (`NaN`).
  - Count the missing values in the `authorities_contacted` column.
  - Fill the missing values in the `authorities_contacted` column with the value "Not Contacted".

6. Time-Based Analyses
- **Task**: Work with time data.
  - Convert the `incident_date` column to date format (`datetime`).
  - Find out in which month the most incidents occurred.
  - Display all incidents reported between February 15, 2015, and February 28, 2015.

In [122]:
damage_df = pd.read_csv("https://raw.githubusercontent.com/DeutscheAktuarvereinigung/Python_fuer_Aktuare/refs/heads/completed/data/car_insurance_claims.csv")
damage_df

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,?,87200,17440,8720,61040,Honda,Accord,2006,N,NaN
996,285,41,186934,2014-01-05,IL,100/300,1000,1436.79,0,608177,...,?,108480,18080,18080,72320,Volkswagen,Passat,2015,N,NaN
997,130,34,918516,2003-02-17,OH,250/500,500,1383.49,3000000,442797,...,YES,67500,7500,7500,52500,Suburu,Impreza,1996,N,NaN
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,YES,46980,5220,5220,36540,Audi,A5,1998,N,NaN
999,456,60,556080,1996-11-11,OH,250/500,1000,766.19,0,612260,...,?,5060,460,920,3680,Mercedes,E400,2007,N,NaN

In [126]:
damage_df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [127]:
damage_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 40 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   months_as_customer           1000 non-null   int64
 1   age                          1000 non-null   int64
 2   policy_number                1000 non-null   int64
 3   policy_bind_date             1000 non-null   object
 4   policy_state                 1000 non-null   object
 5   policy_csl                   1000 non-null   object
 6   policy_deductable            1000 non-null   int64
 7   policy_annual_premium        1000 non-null   float64
 8   umbrella_limit               1000 non-null   int64
 9   insured_zip                  1000 non-null   int64
 10  insured_sex                  1000 non-null   object
 11  insured_education_level      1000 non-null   object
 12  insured_occupation           1000 non-null   object
 13  insured_hobbies              1000 non-null   object
 14  insured_relationship         1000 non-null   object
 15  capital-gains                1000 non-null   int64
 16  capital-loss                 1000 non-null   int64
 17  incident_date                1000 non-null   object
 18  incident_type                1000 non-null   object
 19  collision_type               1000 non-null   object
 20  incident_severity            1000 non-null   object
 21  authorities_contacted        909 non-null    object
 22  incident_state               1000 non-null   object
 23  incident_city                1000 non-null   object
 24  incident_location            1000 non-null   object
 25  incident_hour_of_the_day     1000 non-null   int64
 26  number_of_vehicles_involved  1000 non-null   int64
 27  property_damage              1000 non-null   object
 28  bodily_injuries              1000 non-null   int64
 29  witnesses                    1000 non-null   int64
 30  police_report_available      1000 non-null   object
 31  total_claim_amount           1000 non-null   int64
 32  injury_claim                 1000 non-null   int64
 33  property_claim               1000 non-null   int64
 34  vehicle_claim                1000 non-null   int64
 35  auto_make                    1000 non-null   object
 36  auto_model                   1000 non-null   object
 37  auto_year                    1000 non-null   int64
 38  fraud_reported               1000 non-null   object
 39  _c39                         0 non-null      float64
dtypes: float64(2), int64(17), object(21)
memory usage: 312.6+ KB

In [128]:
damage_df.describe()

,months_as_customer,age,policy_number,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,capital-gains,capital-loss,incident_hour_of_the_day,number_of_vehicles_involved,bodily_injuries,witnesses,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_year,_c39
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,0.0
mean,203.954000,38.948000,546238.648000,1136.000000,1256.406150,1.101000e+06,501214.488000,25126.100000,-26793.700000,11.644000,1.83900,0.992000,1.487000,52761.94000,7433.420000,7399.570000,37928.950000,2005.103000,NaN
std,115.113174,9.140287,257063.005276,611.864673,244.167395,2.297407e+06,71701.610941,27872.187708,28104.096686,6.951373,1.01888,0.820127,1.111335,26401.53319,4880.951853,4824.726179,18886.252893,6.015861,NaN
min,0.000000,19.000000,100804.000000,500.000000,433.330000,-1.000000e+06,430104.000000,0.000000,-111100.000000,0.000000,1.00000,0.000000,0.000000,100.00000,0.000000,0.000000,70.000000,1995.000000,NaN
25%,115.750000,32.000000,335980.250000,500.000000,1089.607500,0.000000e+00,448404.500000,0.000000,-51500.000000,6.000000,1.00000,0.000000,1.000000,41812.50000,4295.000000,4445.000000,30292.500000,2000.000000,NaN
50%,199.500000,38.000000,533135.000000,1000.000000,1257.200000,0.000000e+00,466445.500000,0.000000,-23250.000000,12.000000,1.00000,1.000000,1.000000,58055.00000,6775.000000,6750.000000,42100.000000,2005.000000,NaN
75%,276.250000,44.000000,759099.750000,2000.000000,1415.695000,0.000000e+00,603251.000000,51025.000000,0.000000,17.000000,3.00000,2.000000,2.000000,70592.50000,11305.000000,10885.000000,50822.500000,2010.000000,NaN
max,479.000000,64.000000,999435.000000,2000.000000,2047.590000,1.000000e+07,620962.000000,100500.000000,0.000000,23.000000,4.00000,2.000000,3.000000,114920.00000,21450.000000,23670.000000,79560.000000,2015.000000,NaN

In [133]:
average_damage = damage_df['total_claim_amount'].mean()
average_damage

np.float64(52761.94)

In [134]:
damage_df['policy_annual_premium'].min()

433.33

In [135]:
damage_df['policy_annual_premium'].max()

2047.59

In [146]:
damage_df['claim_ratio'] =  damage_df['total_claim_amount']/damage_df['policy_annual_premium']

In [149]:
damage_df[['total_claim_amount', 'policy_annual_premium', 'claim_ratio']]

     total_claim_amount  policy_annual_premium  claim_ratio
0                 71610                1406.91    50.898778
1                  5070                1197.22     4.234811
2                 34650                1413.14    24.519864
3                 63400                1415.74    44.782234
4                  6500                1583.91     4.103769
..                  ...                    ...          ...
995               87200                1310.80    66.524260
996              108480                1436.79    75.501639
997               67500                1383.49    48.789655
998               46980                1356.92    34.622527
999                5060                 766.19     6.604106

[1000 rows x 3 columns]

In [152]:
damage_df[damage_df['incident_type'] == "Single Vehicle Collision"]

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39,claim_ratio
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,71610,6510,13020,52080,Saab,92x,2004,Y,NaN,50.898778
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN,44.782234
8,27,33,485665,1997-02-05,IL,100/300,500,1442.99,0,601734,...,27700,2770,2770,22160,Toyota,Camry,2012,N,NaN,19.196252
9,212,42,636550,2011-07-25,IL,100/300,500,1315.68,0,600983,...,42300,4700,4700,32900,Saab,92x,1996,N,NaN,32.150675
10,235,42,543610,2002-05-26,OH,100/300,500,1253.12,4000000,462283,...,87010,7910,15820,63280,Ford,F150,2002,N,NaN,69.434691
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,286,43,663190,1994-02-05,IL,100/300,500,1564.43,3000000,477644,...,34290,3810,3810,26670,Jeep,Grand Cherokee,2013,N,NaN,21.918526
991,257,44,109392,2006-07-12,OH,100/300,1000,1280.88,0,433981,...,46980,0,5220,41760,Accura,TL,2002,N,NaN,36.677909
995,3,38,941851,1991-07-16,OH,500/1000,1000,1310.80,0,431289,...,87200,17440,8720,61040,Honda,Accord,2006,N,NaN,66.524260
996,285,41,186934,2014-01-05,IL,100/300,1000,1436.79,0,608177,...,108480,18080,18080,72320,Volkswagen,Passat,2015,N,NaN,75.501639
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,46980,5220,5220,36540,Audi,A5,1998,N,NaN,34.622527

In [157]:
damage_df[(damage_df['incident_state'] == "NY") &
          (damage_df['total_claim_amount'] > 10000)
          ]

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39,claim_ratio
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN,24.519864
6,137,34,413978,2000-06-04,IN,250/500,1000,1333.35,0,441716,...,78650,21450,7150,50050,Nissan,Pathfinder,2012,N,NaN,58.986763
10,235,42,543610,2002-05-26,OH,100/300,500,1253.12,4000000,462283,...,87010,7910,15820,63280,Ford,F150,2002,N,NaN,69.434691
16,70,26,558938,2005-06-08,OH,500/1000,1000,1199.44,5000000,619884,...,52110,5790,5790,40530,Nissan,Maxima,2012,N,NaN,43.445274
18,160,37,921202,2014-12-28,OH,500/1000,500,1374.22,0,472135,...,72930,6630,13260,53040,Accura,TL,2015,N,NaN,53.070105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,50,44,525862,2000-10-18,OH,250/500,2000,1188.51,0,447469,...,61100,6110,12220,42770,Dodge,Neon,2008,N,NaN,51.408907
982,230,43,490514,2007-02-09,IN,500/1000,2000,1101.83,0,451529,...,51900,5190,10380,36330,BMW,M5,2011,Y,NaN,47.103455
988,295,46,591269,1999-01-09,IN,100/300,500,1672.88,0,478947,...,60700,12140,6070,42490,Honda,Civic,1997,N,NaN,36.284731
990,286,43,663190,1994-02-05,IL,100/300,500,1564.43,3000000,477644,...,34290,3810,3810,26670,Jeep,Grand Cherokee,2013,N,NaN,21.918526
998,458,62,533940,2011-11-18,IL,500/1000,2000,1356.92,5000000,441714,...,46980,5220,5220,36540,Audi,A5,1998,N,NaN,34.622527

## Tasks: Analyses of the Titanic Dataset

*Note* The link to the online storage location of the data is:
https://raw.githubusercontent.com/DeutscheAktuarvereinigung/Python_fuer_Aktuare/refs/heads/completed/data/titanic_train.csv

1. **Who was the youngest passenger?**  
   Determine the age of the youngest passenger on board the Titanic. What else can you find out about this passenger?

2. **Survival rate by gender**  
   Investigate whether survival on the Titanic was related to the gender of the passengers. Calculate the survival rate for men and women separately. Use the `Survived` and `Sex` columns for this.

3. **Survival chances in different classes**  
   Did the class in which a passenger traveled influence their chances of survival? Calculate the survival rate for each of the three classes (`Pclass`) and interpret the results.

4. **Average ticket prices per class**  
   Find out how much passengers paid on average for their tickets in each class. Use the `Pclass` and `Fare` columns to calculate the average ticket prices.

5. **Largest families on board**  
   Determine how many siblings and parents (columns `SibSp` and `Parch`) the passengers had on board. Who traveled with the largest family?

6. **Where did most passengers embark?**  
   Investigate which port (`Embarked`) most passengers boarded from.

7. **Distribution of age groups**  
   Divide the passengers into different age groups (e.g., children, teenagers, adults, seniors) and examine how these groups affect the survival rate.

8. **Most valuable ticket on board**  
   Find out which was the most expensive ticket (`Fare`) on the Titanic and who purchased it.

In [120]:
titanic_df = pd.read_csv("https://raw.githubusercontent.com/DeutscheAktuarvereinigung/Python_fuer_Aktuare/refs/heads/completed/data/titanic_train.csv")
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q